style: {
  fill: transparent
}

app: "CLI\nHelpers" {
  shape: square
  width: 128
  height: 128
  style: {
    fill: "#383838"
    stroke: transparent
    stroke-width: 0
    border-radius: 28
    font-color: "#ffffff"
    font-size: 24
    bold: true
    font: mono
  }
}
